from typing import List, Optional, Any

"""
Type Stubs for kenate_bindings
These provide IDE autocomplete support for the C++ compiled module.
"""

class BaseState:
    name: str
    engine: Optional['Engine']
    def __init__(self, name: str) -> None: ...
    def on_enter(self) -> None: ...
    def on_update(self) -> None: ...
    def on_exit(self) -> None: ...
    def get_height_sensor(self) -> float: ...
    def get_distance_sensor() -> float: ...
    def get_battery_level() -> float: ...
    def get_system_temperature() -> float: ...
    def get_signal_strength() -> float: ...

class SafetyState(BaseState):
    def __init__(self) -> None: ...

class Engine:
    def __init__(self) -> None: ...
    def add_state(self, state: BaseState) -> None: ...
    def set_state(self, name: str) -> None: ...
    def start(self, initial_state: str) -> None: ...
    def stop(self) -> None: ...
    def set_frequency(self, hz: float) -> None: ...

class MotorInterface:
    name: str
    def set_velocity(self, velocity: float) -> None: ...
    def set_position(self, position: float) -> None: ...
    def set_effort(self, effort: float) -> None: ...
    def get_velocity(self) -> float: ...
    def get_position() -> float: ...
    def get_effort() -> float: ...

class MockMotor(MotorInterface):
    def __init__(self, name: str) -> None: ...
